version: "3.7"

services:
  fuseki:
    image: stain/jena-fuseki:4.0.0
    ports:
      - 3030:3030
    volumes:
      - ../../data/fuseki:/fuseki
      - ../../data/fuseki-data:/staging
    environment:
      - TDB=2
      - ADMIN_PASSWORD=admin

  es-tp:
    image: es_apollo_test
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ../../data/es-apollo-data:/data